### ISSUE TITLE
Library HX711

### ISSUE THREAD

**Issue by vejo17** [bogde/HX711#10]
Hi Good night i have problem with the code that you use when i try to upload the code, the program send me this message sketch_sep07a:6: error: 'Hx711' does not name a type
sketch_sep07a.ino: In function 'void setup()':
sketch_sep07a:11: error: 'scale' was not declared in this scope
sketch_sep07a.ino: In function 'void loop()':
sketch_sep07a:16: error: 'scale' was not declared in this scope
And i already uploaded the library that you put in web page

I hope can you help me with this issue.

Thanks.
Regards

**Comment by r-a-i** [comment]
I ran into this issue too. 

The documentation on ./README.md says that in the non-blocking mode we should:
```
// 4. Acquire reading without blocking
if (scale.wait_ready_timeout(1000)) {...
```

Instead, it should say:
```
// 4. Acquire reading without blocking
if (loadcell.wait_ready_timeout(1000)) {...
```
for consistency with the definition at the start of the example
```HX711 loadcell;```

**Comment by amotl** [comment]
Dear @r-a-i,

may I humbly ask for a pointer where you found this inconsistency? I just skimmed [1] and can't find any typo in there.

With kind regards,
Andreas.

[1] https://github.com/bogde/HX711/tree/master/examples

**Comment by amotl** [comment]
> may I humbly ask for a pointer

Reading things more concentrated always makes sense. Sorry again for overlooking your reference to `README.md`.

You are absolutely right. When fixing this, we might also think about making the example in README.md consistent with the example files referenced above, right?

Would you personally prefer `scale` oder `loadcell` as the name for a canonical variable name referencing the HX711 object? Technically, just calling it `hx711` will also be fine.

**Comment by r-a-i** [comment]
Dear @amotl, I just submitted a pull request for this change for your consideration. 

Personally, I think the variable name "loadcell" is more generic as the "Hx711" is a loadcell amplifier. Some people may use loadcells to build "scales", but not always. In my case, I'm using a loadcell to measure a force directly and not weight. 

Thank you for your consideration and all your contributions to this library.
