### ISSUE TITLE
Hx711 Max resolution 

### ISSUE THREAD

**Issue by humble14** [bogde/HX711#106]
I been using HX711 successfully upto 4 50Kg load cells which is equal to 440 lbs of weight.

Now I intend to use it [with](https://www.ebay.co.uk/itm/100-300-2000-5000Kg-Universal-Electronic-Weighing-Sensor-Scale-Cell-Weight-Metal/382422626447?hash=item590a2a308f:m:mdCfQ2K_Qkx8RDzIxe0JJ3w) 2000kG load cell

Firstly is there a way to increase the resolution of hx711 to the high load needs ? Secondly is HX711 is appropriate for this type of load cell ?

**Comment by MyrthosM** [comment]
The resolution will be the same for any load cell 24-Bits. HX711 is ADC converter don't worry about resolution, to HX711 can handle it, as long as your load cell is powered within the power range of the ADC.
