### ISSUE TITLE
The lib doesn't seem to be working on the Arduino Due

### ISSUE THREAD

**Issue by ThibaudAV** [bogde/HX711#112]
The lib doesn't seem to be working on the Arduino Due.

No compilation error but the code is blocked at the instantiation of the lib :/

Do you have the same problem?

**Comment by bogde** [comment]
unfortunately i dont have a due to test on, and frankly the lib was written with only arduino uno in mind. if i will ever get a due, i'll make sure to test the code and make it work, if possible.
