### ISSUE TITLE
Confused  Signal HX711 with ATMEGA2560

### ISSUE THREAD

**Issue by ijamjun** [bogde/HX711#139]
I read data sheet HX711 Sent Data 24 bit  1 CH and  CLK 1 CH that mean I2C  while I read code why connect with  ADC analog port and I read Library file It very confuse  about  process code , Professsors kildly shed a light or suggest  , Help guide the steps or information for further study.

**Comment by bogde** [comment]
you don't have to use the analog pins, you can use the digital pins if you want.

**Comment by ijamjun** [comment]
Noted,Thanks sir
