### ISSUE TITLE
How to use this lib on an ESP8266-01 ?

### ISSUE THREAD

**Issue by gusantor** [bogde/HX711#141]
Does anybody succeeded implementing this library on an ESP8266-01 ?

I ask because the basic example runs ok on a wemos D1 but not on an ESP8266-01, I receive wrong measures

Please any advice on how to run this HX711 lib on an ESP8266-01 ?, thanks !

**Comment by bogde** [comment]
Most likely this was a pin issue. It has been reported that the GPIO0/D3 pin can't be used: #190
