### ISSUE TITLE
issue regarding function call

### ISSUE THREAD

**Issue by sravyasona** [bogde/HX711#144]
no matching function for call to 'HX711:: HX711(int, int)'. could any help me with this issue? I'm new to the Arduino

**Comment by mark-zacharias** [comment]
I ran into the same thing, itlooks like you are using the [old example code](https://github.com/bogde/HX711#deprecation-warning).

**Comment by amotl** [comment]
Dear @sravyasona and @mark-zacharias,

this is true, the constructor changed. You would now access the library like outlined within https://github.com/bogde/HX711#synopsis.

With kind regards,
Andreas.

**Comment by bogde** [comment]
Closing due to lack of feedback.
