### ISSUE TITLE
Calibration tips

### ISSUE THREAD

**Issue by GoncaloFelicio** [bogde/HX711#145]
Hi!
I would like to know more about calibration. Is specific, does the setup influence the calibration factor, or is the calibration factor a number i get from the calibration sketch and then i always use that same calibration factor?

In my case, i want to setup 4 loadcells to the same wood board, but can i calibrate before i screw them to the board, or can i only calibrate after i have my setup?

Thanks!

**Comment by bogde** [comment]
I apologize for not replying in time. I will leave my thoughts here now, in case anyone else has the same question. I would say you can't use the method outlined in the readme file in order to calibrate, without completing your setup first. However, this post may help you out: #20
