### ISSUE TITLE
Can't upload to Arduino

### ISSUE THREAD

**Issue by pgiguere1** [bogde/HX711#16]
I have an existing sketch that successfully uploads to my Arduino Yún over USB.
If however I include this library and add the `HX711 scale(A1, A0);` line, I can't upload it anymore.

I'll click upload, the status LED will start blinking, then `/dev/cu.usbmodem1421 (Arduino Yún)` will disappear from my port list and I'll get a `Board at /dev/cu.usbmodem1421 is not available` error message.

I tried resetting the Arduino and pressing reset right after initiating the upload to no avail. The only way to actually upload and run my sketch is to comment out the `HX711 scale(A1, A0);` line.

I'm not really sure how to debug this and tell whether software or hardware is to blame. I tried printing something to serial at the very first line of HX711's constructor, but I can't even get this to show up in Serial Monitor.

**Comment by bogde** [comment]
I'm sorry but the library wasn't designed nor tested on Arduino Yún.
