### ISSUE TITLE
Find the correct calibration factor at powerup using a know weight ? 

### ISSUE THREAD

**Issue by hjojohan** [bogde/HX711#167]
Hi 
I would like to see a code example that could find out the calibration factor at Arduino powerup using a known weight type 1 kg. The initializing code should loop by itself until the calibration factor is found and the store the factor in eeprom on a arduino.   From my experience the SCALE needs recalibration everytime you move it, I tried to send the scale by freight forwarder 'DHL' to a another site and the scale measurements where not good when the scale arrived. 

For example : Use a LED to signal (flashing) to inform enduser that the Arduino is in 'calibration mode' and a known weight should be placed on the scale and when calibration is done by code the LED light should turn solid and after this the scale is ready for normal operation

Is there a kind soul out the that could give me sample code to look at ?

I want to avoid the manual approach below, and let the code in/decrease until the calibration factor found  
###############################################################
  Serial.println("Place known weights on scale one by one.");
  Serial.println("Press '+' to increase calibration factor by 10");
  Serial.println("Press '-' to decrease calibration factor by 10");
  Serial.println("Press 'C' for tare");
################################################################

**Comment by simpat1zq** [comment]
Not sure if it would help you. But I made a web interface for the ESP8266 that handles calibration with a wizard.:

https://automatedhome.party/2019/12/14/the-filaweigher-a-standalone-wifi-web-based-weight-sensor-for-3d-printer-filament-for-less-than-7/

**Comment by bogde** [comment]
@simpat1zq Thanks for your help!

Closing due to lack of additional feedback.
