### ISSUE TITLE
no matching function for call to 'HX711::HX711()'

### ISSUE THREAD

**Issue by AyamTepihit** [bogde/HX711#175]
Issue persist even after following the example given.

**Comment by AyamTepihit** [comment]
#include <HX711.h>

const int LOADCELL_DOUT_PIN = 3;
const int LOADCELL_SCK_PIN = 2;

HX711 scale;

example of the code i used. the error occur on the line HX711 scale;

**Comment by AyamTepihit** [comment]
![errorcal](https://user-images.githubusercontent.com/38453996/77252016-b10f1b80-6c8c-11ea-8188-890e7efabfb0.png)

image included is the code i used exactly in the example

**Comment by amotl** [comment]
Dear @AyamTepihit,

will `#include <HX711.h>` work for you? I see you closed the issue alread: Did things start working for you?

With kind regards,
Andreas.

**Comment by AyamTepihit** [comment]
Currently I am using other library works for my coding. I already tried changing into #include <HX711.h> still no luck, for now other library works fine, maybe I’ll fix my issue with your library soon after I calibrate my load cell with other library first.

Thanks anyway for helping my issue. I’ll contact you if there is another issue.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
