### ISSUE TITLE
HX711 Inconsistent/negative data? Please Help!

### ISSUE THREAD

**Issue by popcornkernel** [bogde/HX711#189]
I'm trying to fill an array with load cell values, but first I'm starting by just getting values. The values are extremely inconsistent and sometimes get stuck at a random value (see bottom for random values ). Any idea on what to do? (I'm a very poor programmer, any help is appreciated) 

`#include "HX711.h"

HX711 scale;

void setup() {
  Serial.begin(38400);
  Serial.println("HX711 Demo");

  Serial.println("Initializing the scale");
  // parameter "gain" is ommited; the default value 128 is used by the library
  // HX711.DOUT  - pin #A1
  // HX711.PD_SCK - pin #A0
  scale.begin(A1, A0);

  Serial.print("Raw ave(20): \t\t");
  Serial.println(scale.read_average(20));   // print the average of 20 readings from the ADC

  // Scale factor:
  // 1Kg cell: 2020 for reading in gms
  // 50kg cells: 19150 for reading in kg
  scale.set_scale(2020.f);                      // this value is obtained by calibrating the scale with known weights; see the README for details
  scale.tare();               // reset the scale to 0

  Serial.println("\nAfter setting up the scale:");

  Serial.print("Raw: \t\t\t");
  Serial.println(scale.read());                 // print a raw reading from the ADC

  Serial.print("Raw ave(20): \t\t");
  Serial.println(scale.read_average(20));       // print the average of 20 readings from the ADC

  Serial.print("Raw ave(5) - tare: \t");
  Serial.println(scale.get_value(5));   // print the average of 5 readings from the ADC minus the tare weight, set with tare()

  Serial.print("Calibrated ave(5): \t");
  Serial.println(scale.get_units(5), 1);        // print the average of 5 readings from the ADC minus tare weight, divided
            // by the SCALE parameter set with set_scale

  Serial.println("\nReadings:");
}

void loop() {
  Serial.print("one reading:\t");
  Serial.print(scale.get_units(), 1);
  Serial.print("\t| average:\t");
  Serial.println(scale.get_units(10), 1);

  scale.power_down(); // put the ADC in sleep mode
  delay(5);
  scale.power_up();
 }`

Here is the weird data:
HX711 Demo
Initializing the scale
Raw ave(20): 		2879904.00

After setting up the scale:
Raw: 			2875102.00
Raw ave(20): 		2876889.50
Raw ave(5) - tare: 	277.25
Calibrated ave(5): 	0.7

Readings:
one reading:	1.0	| average:	0.9
one reading:	-0.1	| average:	-0.7
one reading:	-3.1	| average:	-3.1
one reading:	-2.4	| average:	-2.2
one reading:	-2.4	| average:	-1.8
one reading:	-2.6	| average:	-1.8
one reading:	-1.1	| average:	-0.3
one reading:	-1.8	| average:	-2.2
one reading:	-2.0	| average:	-1.0
one reading:	-4.8	| average:	-4.3
one reading:	-5.2	| average:	-9.5
one reading:	-8.1	| average:	-6.8
one reading:	-1.7	| average:	-3.9
one reading:	-7.8	| average:	-9.6
one reading:	-26.6	| average:	-27.1
one reading:	-25.3	| average:	-25.1
one reading:	-25.6	| average:	-27.2
one reading:	-27.8	| average:	-27.9
one reading:	-26.8	| average:	-27.4
one reading:	-22.3	| average:	1119.7
one reading:	2729.3	| average:	2729.3
one reading:	2729.3	| average:	2729.3
one reading:	2729.3	| average:	2729.3
one reading:	2729.3	| average:	2729.3
one reading:	2729.3	| average:	2729.3
one reading:	-157.2	| average:	-532.6
one reading:	-1101.7	| average:	54.4
one reading:	-787.1	| average:	-755.3
one reading:	-687.9	| average:	-680.1
one reading:	-658.1	| average:	-527.5
one reading:	-529.1	| average:	-533.6
one reading:	-534.3	| average:

**Comment by bogde** [comment]
what happens if you're using a larger delay, like 500 millis instead of 5 millis?
