### ISSUE TITLE
HX711 interface with esp32

### ISSUE THREAD

**Issue by Jayendrarnaik** [bogde/HX711#192]
hello ,,,
i tried interfacing 20kg load with esp32 uisng hx711 module, but am not able make it correctly. I programed esp32 with basic example but hx711 is not getting detected. Tried the same hx711 with arduino mega adk ...its working prefectly.
esp23 pin:
dout-25
sck-22
(tried with almost all the pins avilable in eps32 :( )
![WhatsApp Image 2020-12-09 at 4 37 10 PM (1)](https://user-images.githubusercontent.com/48217595/101622556-35811480-3a3d-11eb-9fea-f8618b4d778a.jpeg)
![WhatsApp Image 2020-12-09 at 4 37 10 PM](https://user-images.githubusercontent.com/48217595/101622562-374ad800-3a3d-11eb-9a9b-9c384d68579f.jpeg)
please help....

**Comment by bogde** [comment]
Did you solve this? The library has been tested with ESP32 and it worked. Are you sure your pins are correctly set up? Can you test the pin definitions with something else, like an LED, just to make sure the wiring is right?

**Comment by bogde** [comment]
Closing due to lack of further feedback.
