### ISSUE TITLE
HX711 with load cell

### ISSUE THREAD

**Issue by Pathmashantha-bit** [bogde/HX711#194]
I compiled my Arduino code. It shows this error. "no matching function for call to 'HX711::HX711()'". Please help me. My Arduino code is bellow.

#include "HX711.h"

// HX711 circuit wiring
const int LOADCELL_DOUT_PIN = 2;
const int LOADCELL_SCK_PIN = 3;

HX711 scale;

void setup() {
  Serial.begin(9600);
  scale.begin(LOADCELL_DOUT_PIN, LOADCELL_SCK_PIN);
}

void loop() {

  if (scale.is_ready()) {
    long reading = scale.read();
    Serial.print("HX711 reading: ");
    Serial.println(reading);
  } else {
    Serial.println("HX711 not found.");
  }

  delay(1000);
  
}

**Comment by mal-w** [comment]
Sounds to me like you might not have installed the library, is that possible?

In case you haven't, here is the link to [how to install libraries for Arduino](https://www.arduino.cc/en/Guide/Libraries).
