### ISSUE TITLE
Cryptic message in serial monitor

### ISSUE THREAD

**Issue by FerdZNerd** [bogde/HX711#212]
I am clearly doing something wrong. 
what could be the reason for me getting this in the serial monitor. 
I do not get anything else. 

![serialmonitor](https://user-images.githubusercontent.com/33283320/134525232-0e38d958-83fa-49e9-92a5-579c4b5ceb07.png)

**Comment by bogde** [comment]
did you check baud rate?

**Comment by FerdZNerd** [comment]
I have the 9600 baud in the monitor. 
I have tried different rates both higher and lower, but unfortunately I get the same error.

**Comment by FerdZNerd** [comment]
Ok, now I change the baud rate to 9600, in the code and the serial monitor. 
Thanks, I made some progress but now i got the issues of HX711 not found.
