### ISSUE TITLE
it is work,but can not reboot

### ISSUE THREAD

**Issue by EagleSmith** [bogde/HX711#22]
Your code works well, but there is a problem with all HX711 connected to espduino(like nodemcu), esprduino can not reboot and boot, do you encounter this problem?
Thanks

**Comment by bogde** [comment]
no, because i'm not using espduino. the code has been tested only on (a limited number of) atmega based boards. good luck with your project!

**Comment by joelseverin** [comment]
HX711.cpp uses a busy-wait loop to wait for values (delivered 10 or 80 times per second), similar to a long delay(). This is not popular on the esp. I think you could get away with putting a yield() (or whatever it is called) in that loop, so that the esp can perform its other duties.

**Comment by CFTechno** [comment]
you can use a  " if (scale.is_ready())" statement to read the scale . That way it doesn't go into the while loop when requesting a value

**Comment by EagleShi** [comment]
hi all,thank you for your help,it is working now.
