### ISSUE TITLE
Error on `make build-all`

### ISSUE THREAD

**Issue by gamename** [bogde/HX711#259]
Hi,

I'm getting this when I try to build the examples:
```make build-all
/bin/sh: --python=python3: command not found
make: *** [setup-virtualenv] Error 127
```

Any ideas?

I'm using zsh on MacOS 14.2.1 (23C71)

**Comment by darkb0ts** [comment]
Check Python Installation like this ``` python3 --version``` and  Use Virtual Environment (Recommended):

It's recommended to use a virtual environment to isolate project dependencies. This prevents conflicts with other Python installations on your system.
Tools like venv or virtualenv can be used to create virtual environments. Here's an example using venv:
Bash
python3 -m venv my_env  # Create a virtual environment named "my_env"
source my_env/bin/activate  # Activate the virtual environment
