### ISSUE TITLE
read function is slow

### ISSUE THREAD

**Issue by leszek77** [bogde/HX711#31]
Hello when i use the function get_units() in my code
then the programm slows very down.
i have figured out this is caused by
long HX711::read() {
	// wait for the chip to become ready
	while (!is_ready()); <<<<<<<<<<<<<<<<<<<<<<<<<<<< HERE

i think it need to be rewritten with attachinterupt or timer?

**Comment by leszek77** [comment]
I have study this code. Now I quite understand your code. The issue is that you try to get all bits in one cyclus of the main function loop. This cause trouble and the CPU Idle a lot and this slow my other code down. 
Now i have started a new approuch one bit each cycle. 

const byte hx711_data_pin = A7;
const byte hx711_clock_pin =A6;
bool  bOut,bOut1,bOut2;
bool  bIn,newData,readingHX;
byte data1,data2,data3;
unsigned long currentTime;
unsigned long lastUpdate1,lastUpdate2;
int i,d,j;
long int dd;
void setup() {
  // put your setup code here, to run once:

  pinMode(hx711_clock_pin,OUTPUT);
  pinMode(hx711_data_pin,INPUT);
 // digitalWrite(hx711_data_pin, HIGH);
  Serial.begin(9600);
  readingHX=1;
}

void loop() {


if(readingHX){
  if(bOut2){
    bOut2=0;
    digitalWrite(hx711_clock_pin,0);  
  }else{
    bOut2=1;
    digitalWrite(hx711_clock_pin,1);  
    bIn=digitalRead(hx711_data_pin); 
    j=23-i;
    if(i<24){
      dd |= bIn<<(j);     
    }
    i++;
  }
}else{
 i=0;
}
if(i==24){
  readingHX=0;
  dd ^= 0x80;
  Serial.println(dd,BIN);
  dd=0;
  digitalWrite(hx711_clock_pin,0);    
}
}

**Comment by CFTechno** [comment]
Would it not been easier to use
`
 if (scale.is_ready()) Lvalue = scale.read() ;
`

**Comment by bogde** [comment]
@leszek77 do you still need any help with this?

**Comment by leszek77** [comment]
yes, but i try to figure out by my self.

**Comment by kasperv79** [comment]
Hi.
@leszek77, did you finalise your version?

**Comment by leszek77** [comment]
i didn\t continue to work on it

**Comment by theharshalpatil** [comment]
@bogde I'm facing the same issue. Is there a way to increase the speed at which the data is fetched?

**Comment by Srijal97** [comment]
For anyone reading this in the future, that `while (!is_ready());` in `read()` caused the code to block and would waste a lot of processor cycles so I modified it by removing the while loop, and instead repeatedly checking in the main loop if chip `is_ready()`. I created separate functions `read_direct()` [Without the blocking while loop], and `get_units_direct()` [Which calls read_direct() directly] and added this to my main loop:
```
if (scale.is_ready()){
    tension = scale.get_units_direct();
}
```

**Comment by MugetsuX** [comment]
@Srijal97 Hey there, i'm facing the same problem with the _while (!is_ready());_ function. I'm not a programmer and can't figure out how to change the while loop to an if function. Could you give some more detail on how you have set up your code? I'm using the multi-library to connect 4 loadcells:
https://github.com/compugician/HX711-multi/blob/master/HX711-multi.cpp

Thanks a lot :-)

**Comment by Srijal97** [comment]
@MugetsuX Hey, if you could just drop me an email on the ID from my GitHub profile, I'll send you the modified library and example code showing what I mean!

**Comment by jeroentjeee** [comment]
@Srijal97 Hi Sir, I tried your way of fixing this problem, however i'm not quite getting it done. could you also send me the modified libraby?

thanks a lot

**Comment by andrelouk** [comment]
@Srijal97 could you send me your modifications to the library. thank you very much.. im doing a rapid acquisition from the load cell, and i need to get the value as fast as possible. Thank you very much..

**Comment by Srijal97** [comment]
> @Srijal97 could you send me your modifications to the library. thank you very much.. im doing a rapid acquisition from the load cell, and i need to get the value as fast as possible. Thank you very much..

Please find the files here: [Google Drive - HX711](https://goo.gl/Ys3Ycv)

**Comment by andrelouk** [comment]
Thank you Very Much... Really Appreciate it

**Comment by eleksis** [comment]
@Srijal97 thanks for sharing the code. If i can suggest...you should make fork of this project and publish your code on your github profile, that's what github is for...

**Comment by Srijal97** [comment]
> @Srijal97 thanks for sharing the code. If i can suggest...you should make fork of this project and publish your code on your github profile, that's what github is for...

I have done that now, thank you!
