### ISSUE TITLE
need help measuring milligram weight

### ISSUE THREAD

**Issue by sfaisol** [bogde/HX711#37]
is there any function that i can call to get milligram weight, my object is very small and my milligram load cell is connected to a HX711.

Thank you.

**Comment by bogde** [comment]
if you follow the calibration procedure with a (very small) known weight, you will then be able to get the values you want.

or you can refer to @Bartimaeus' very competent comment here: https://github.com/bogde/HX711/issues/20 and you should be able correctly calculate the scale correction value.
