### ISSUE TITLE
Default values for OFFSET and SCALE.

### ISSUE THREAD

**Issue by obiwan-bartek** [bogde/HX711#42]
Hi,
I suggest to add a default values for OFFSET (as 0), and for SCALE (as 1), to be able to use .get_units() without first setting them in code.

**Comment by bogde** [comment]
can you elaborate on that? using get_units for a SCALE of 1 won't make much sense i think...

**Comment by ReDetection** [comment]
I can. Currently SCALE is 0 at start, so when you try to get units, it reports infinity, which is a result of anything divided by zero. This is a way less sense than have default scale of one 😉

**Comment by bogde** [comment]
Good point, thanks for clarifying. I was thinking you wanted something that will give you grams or kilograms by default. I'll make the changes asap.

**Comment by bogde** [comment]
This should be fixed in 38f8ff0bda29b2377a9a6d3fe3eb25690c05bbe2.
