### ISSUE TITLE
Read Rate adjustable via sketch?

### ISSUE THREAD

**Issue by petewilk** [bogde/HX711#46]
Using the Sparkfun breakout board and this library is the read data rate adjustable?  Looking at the HX711 schematic it looks like the default rate is 10SPS, which seems likely given the rate data gets spit out to the serialprint.  Via the library is it possible to change to 80SPS?  Yes, there would be more noise, but I'd like to try it to see if the noise is acceptable for my application.

**Comment by electrokean** [comment]
Setting the rate is done via an input pin "RATE" on the HX711 (pin 15)
If you're talking about this breakout: https://www.sparkfun.com/products/13879
Then on the back of the PCB is a solder jumper that you need to cut to change the rate to 80sps
You can see this in the Sparkfun schematic - the jumper SJ2 pulls RATE to GND (0 for 10sps), but there is a pullup resistor to connect RATE to VCC (1 for 80sps).
