### ISSUE TITLE
Current master does not work

### ISSUE THREAD

**Issue by ReDetection** [bogde/HX711#47]
I spend almost a day trying to figure out why I receive random readings. I checked wiring several times, each pair of load cells, etc, until I tried another HX711 library which worked great but does not have a powerdown mode and so on. 

I already figured out it's because of pull request #38 (commit 0c444e2 works fine), so probably every issue since that pull request may be related, but I would like to explicitly leave it here until the issue is resolved, so nobody going to spend a lot time in headaches. 

(I have to clarify: I tested on on arduino nano and a single atmega328p MCU)

**Comment by bogde** [comment]
I just reverted the changes introduced by the pull request #38. Thanks for your input and I apologize for wasting your time. If you could test the current master and confirm it's working that would be great. Thanks again!

**Comment by ReDetection** [comment]
Yep, I confirm master branch is working again. Guess we can close the issue.
![screen shot 2016-10-02 at 19 19 43](https://cloud.githubusercontent.com/assets/458005/19020523/1d6a4d58-88d5-11e6-89f6-5e190e362e1f.png)

And thanks for implementation of powerdown! 😴
