### ISSUE TITLE
Strange behavior for arduino newbie

### ISSUE THREAD

**Issue by GHarmata** [bogde/HX711#49]
I tried to run your calibration code with my load cell + hx711 + arduino uno setup.  In the serial monitor, this is what was displayed: 

4����()�)!!�41���%)� �%(��4!���)%4���B��1��%!�0��-�!!�

Any idea where the problem might be?  Thanks!

**Comment by bogde** [comment]
Probably the baud rate in your serial monitor is wrong. It should be 38400.
