### ISSUE TITLE
Issues running this Library on "Energia" with a MSP432

### ISSUE THREAD

**Issue by nanocar** [bogde/HX711#52]
Hello Bogde, 

I tried out your library on an Arduino just to test it out and it works beautifully. I need to use this on an MSP432 that uses Energia, which claims to be an Arduino based IDE. I'm not sure which parts are incompatible but I'm only getting 0 value readings when I run the code. Do you know if there's anything that I should change in order to make them compatible?

Thanks,

**Comment by bogde** [comment]
i never used MSP432, nor Energia, in fact it's the first time i hear about any of them. i doubt i can be of any help, without being able to actually test stuff. if you have an oscilloscope you could try to check the clock and data lines to see if the hx711 responds in any way. a cheap logic analyzer could work too. i have no other ideas right now.
