### ISSUE TITLE
Error Compiling yeild(); not declared in Scope

### ISSUE THREAD

**Issue by Dhawgupta** [bogde/HX711#54]
Showing yield(); not declared in scope for Hx711.cpp

**Comment by bogde** [comment]
A couple more details about your setup? IDE version, target board?

**Comment by shakirullahi** [comment]
I'm getting the same error 

> HX711.cpp:49:9: error: 'yield' was not declared in this scope yield();

I'm using Arduino IDE Version 1.8.5 in Windows 7 and trying to compile for Attiny85 USB development module (Digispark (Default - 16.5mhz).
