### ISSUE TITLE
Hi bogde

### ISSUE THREAD

**Issue by Hariskhalil** [bogde/HX711#58]
i have old tensile testing machine which has been expired, i thought to make that machine for tensile testing using machine's own load cell and mechanical assembly.
i figured out that i need avia semiconductor 24bit adc, arduino, for calibration of load cell( 0.1 mV / V) and your library same power supply.
i am using your library, and i have been working for last 5,6 days and i have frustrated because of no result. 
The issue, i am facing is my load  showing unusual behavior when ever i connect load cell and run basic program(yours) it shows continuously fluctuation values with out even little accuracy.
i have tried a lot with different ways (basic program, changed programmed, etc etc)
Kindly help me to solve issue  
![1](https://cloud.githubusercontent.com/assets/24788635/21641017/cf5df14a-d29a-11e6-98db-76b13e1e1fee.PNG)

above is status pic

**Comment by bogde** [comment]
what happens if you add a delay between readings?

**Comment by Hariskhalil** [comment]
same thing happens , same behavior  
Do u think its load cell issue ? i have also attached  voltage divider 0 to 20 mV using arduino 5V supply to it just for seeing result but i got same behavior .

**Comment by electrokean** [comment]
I suspect a wiring issue or a damaged chip.

You say you attached a voltage divider - how did you do that exactly?
The HX711 is designed to measure a voltage difference of +/-80mV max between the two inputs when at a potential near half the supply voltage.  It isn't designed to measure voltages close to either of the supply rails.  The datasheet says they must be kept above 1.2V, and below the supply less 1.3V.

**Comment by Hariskhalil** [comment]
i used simple voltage divider circuit consist of one resistor & one V.R in series supplied by arduino  5 V supply and its output (approx 0 mV to 22 mV) gave into arduino inputs pins for seeing response after using load cell.

**Comment by electrokean** [comment]
As I mentioned that wont work.
The inputs are differential and require voltages centred at around half your supply voltage, with +/-80mV max differential between the IN+ and IN-.
So for example with a 5V supply INA+ may be 2.501V and INA- 2.499V to get +2mV differential voltage.
Voltages at the inputs less than 1.2V or greater than 1.3V below the supply are outside device specification.

**Comment by Hariskhalil** [comment]
As far as i can understand that you are saying by interfacing voltage divider output signal directly to HX711 module input will not work because it gives only some mV (checked using voltmeter) signal & does not give half of input supply volts to give differential mV signal ?

i had my load cell connected in same manner as in pic 
![wiring](https://cloud.githubusercontent.com/assets/24788635/22362999/e9c0a154-e488-11e6-92bb-251091755d8a.jpg)
it showed same behavior as voltage divider. 

should i change cell or add some circuitry before connecting to Hx711?
if i change cell then what specs should load cell to work properly with Hx711 ?

**Comment by electrokean** [comment]
That wiring looks fine.  It may be that your HX711 board is faulty.  Do you have another one to try?
This is the style of load cell I recommend https://www.sparkfun.com/products/13329
You want a 4 or 6 wire load cell (not 3 wire) and obviously rated to suit your needs.
