### ISSUE TITLE
Cooperation with accelstepper lib

### ISSUE THREAD

**Issue by PacoRaap** [bogde/HX711#6]
Hi, I use the lib with the HX711 as previous amplifier TM7709 could not be obtained anymore.
In my curent project I use a steppermotor and the accelstepper lib.
Both libs work seperate without problem.
But when I put in the void loop a simple line like
ForceValueTemp = (scale.read()/100); 
It blocks the stepper code and reduce the stepper speed to a single tick per second or so.
It looks like the reading of the sensor bloakcs but could not find code in the .h or .cpp that might be the cause.
I need both options together.
Any idea what might be the cause?

Thanks for your time,

Paco

**Comment by jbeuckm** [comment]
Do you know if anyone has done the modifications for faster reads? I tied my RATE pin high for 80hz readings but it's taking about 60ms to read right now - at least while I'm reporting the millisecond count to Serial on each read.

**Comment by electrokean** [comment]
@jbeuckm it has been a while but I recall having it working on my penguin weighbridge.
If you're outputting stuff over serial and doing much other processing, that could be impacting your timing.  And I recall that if you didn't read data fast enough it could get out of sync and you'd get the occasional bad reading.  If you want to share some code I/we could comment further.
