### ISSUE TITLE
[HX711.h] Is "float SCALE = 1;" shouldn't be "float SCALE = 1.f;"?

### ISSUE THREAD

**Issue by obiwan-bartek** [bogde/HX711#66]
In HX711.h main class section, private fields, there is:
`float SCALE = 1;`
Shouldn't it be 
`float SCALE = 1.f;`
as the SCALE is float number?

**Comment by electrokean** [comment]
There are coding examples where not specifying a constant as float could matter, so it would be more correct as you suggest.  But the compiler will automatically cast the integer constant to a float, so it makes no difference here.
