### ISSUE TITLE
READING BOTH CHANNELS .. solved

### ISSUE THREAD

**Issue by dagnall53** [bogde/HX711#77]
I see on various forums questions about reading both channels. 
This is possible, but there are speed implications:
to switch channels you must send the set_gain message, and then allow time for the HX711 to set itself up:

I am using this code `
String readScales(byte Chan){ 
  String Reading;
  int average =2;
  Reading="0";
  if (ScalesConnected()) {
              if (Chan==0){ scale.set_gain(128); //ch A
              Reading=scale.read(); //dummy to get ready
              //CH1scaleset);  this scaling value is obtained by calibrating the scale with known weights; 
              Reading= String (  ((scale.read_average(average)-TAREA)/CH1scaleset) );}
          if (Chan==1){  
              scale.set_gain(32); //ch B
              Reading=scale.read(); //dummy to get ready
              //CH2scaleset);  This value is obtained by calibrating the scale with known weights; 
              Reading= String (  ((scale.read_average(average)-TAREB)/CH2scaleset));}
                          }  
  return Reading;
}`
The boolean ScalesConnected() and Long variavles "TAREA" and "TAREB" are set elsewhere in an "init" routine.. 
I have found that I can get just about two (alternating) readings per second with 'average'= 2.  
If you do not alternate, readings are faster. 

Hope this helps.

**Comment by bogde** [comment]
thanks @dagnall53 for your contribution.
