### ISSUE TITLE
Calibration help

### ISSUE THREAD

**Issue by NZbeek** [bogde/HX711#8]
Hi Bodge,

thanks for the code! I would like to use just basic features of your code, but I am far too inexperienced to know how to change it. I would like to use it to track the weight of a beehive. This means that the weight will start when I place the scales under the hive at eg 100kg then generally increase (but may decrease) up  to ~ 250kg over several weeks.

In that time I would like to use your code to take the total weight twice a day (morning and night) and I will send the weight via GSM.

I am having trouble calibrating - I know I need to change the set_scale figure but I do not now how to get the original reading (which I then divide by the known weight). When you say "call get_units(10)" do I need to enter that line into the sketch code? - or do I use the figure given when running the code in serial monitor from the line?:

Serial.print("\t| average:\t");
  Serial.println(scale.get_units(10), 1);

Because my scales will sleep between readings, I think I need to remove your tare function? - I want the scales to show me the current total weight each time the sketch runs/arduino wakes, however as your script auto tares it reads "0" each time I restart the serial if there is already weight on it. Can I just remove the line?:

scale.tare();

Because I will send the date via GSM, I think I will need to assign the weight to a reference, if you have any ideas how to modify your code to let me do this that would be great, otherwise if you had time to help me with my other issues I would really appreciate it. Thanks for your time.

William

**Comment by vainell** [comment]
can someone please post an example of how to get the kilogram. im using a Human Body scale load cell sensor resistance strain 50kg half-bridge sensors ..

**Comment by kbickham** [comment]
Thanks again for the code, but I am confused. There is no member in the library set
_tare(). I don't expect you to remember every piece of code you've written, but you are referring to the call (for an object instantiated as scale) scale.tare(); correct?

**Comment by bogde** [comment]
@kbickham yes, that's correct. i also updated my comment above.

**Comment by bemar76** [comment]
This sketch could be helpfull:

```
#include "HX711.h"

const int PIN_SCK = 32;
const int PIN_DOUT = 33;

HX711 scale;

float calibration;

void setup() {
  Serial.begin(9600);
  scale.begin(PIN_SCK, PIN_DOUT);

  Serial.println("Please place a known weight on the scale and enter its weight:");

  scale.set_scale(); // this value is obtained by dividing the calibration value with the known weight;
  scale.tare(); // reset the scale to 0

  float m = 0;
  boolean f = 0;

  while (f == 0) {

    if (Serial.available() > 0) {
      m = Serial.parseFloat();
      if (m != 0) {
        Serial.print("Known mass is: ");
        Serial.println(m);
        f = 1;
      }
      else {
        Serial.println("Invalid value");
      }
    }
  }

  float unit = scale.get_units(20);

  Serial.print("Calibration Value: ");

  calibration = unit / m;

  Serial.println(calibration);
}

void loop() {
  Serial.print("Read: ");
  Serial.println(scale.get_units(20) / calibration);

  // scale.power_down(); // put the ADC in sleep mode
  delay(100);
  //  scale.power_up();
}
```
