### ISSUE TITLE
High speed weight sensing

### ISSUE THREAD

**Issue by bc** [bogde/HX711#95]
Working on a muscle tension controller using a load cell, for a musculoskeletal experiment.

I noticed that the HX711 can't record digitally any faster than 80SPS. I'm trying to measure at 1kHz/ 1kSPS. Is there a way to get the analog voltage out of the unit? Are there any alternatives that are a bit faster?
Thanks!
-Brian

**Comment by tk5ep** [comment]
The HX711 is probably not a good choice for your project.
It can't read faster than 80SPS. There is no analog voltage to be read, the output is serial. Anyway, reading a voltage needs a A/D converter, and you're back to your initial need !
